version: '3' 

services: 

    backend:
      build: .
      ports:
        - '8000:8000'
      environment:
        - FRONT_URL=http://localhost:5000

    frontend:
      build: ../frontend-example-docker/
      ports:
        - '5000:5000'
      environment:
        - API_URL=http://localhost:8000