version: '3.5'

services:
    frontend:
      build: ./ml-kurkkumopo-frontend
      ports:
        - 3000:3000
      restart: unless-stopped 

    backend:
      build: ./ml-kurkkumopo-backend
      ports:
        - 5000:5000
      volumes:
        - model:/src/model
      restart: unless-stopped 

    training:
      build: ./ml-kurkkumopo-training
      volumes:
        - imgs:/src/imgs/
        - ./ml-kurkkumopo-training/data:/src/data/
        - model:/src/model/

volumes:
    imgs:
    model: