# not sure if this actually works

version: '3.5'

services:
    frontend:
      build: ./ml-kurkkumopo-frontend

    backend:
      build: ./ml-kurkkumopo-backend
      volumes:
        - /src/models:/ml-kurkkumopo-training/model

    training:
      build: ./ml-kurkkumopo-training
      volumes:
        - /src/imgs:/src/imgs/
        - /data:/data/
        - /model:/model/
      
